### PR TITLE
Fix min_error calculation

### LINKED ISSUE #140: Bug in min_error calculation
residual_error_method is based on mf - mf_mod, but currently mf_mod isn't on the same unit scale as mf. We should first rescale mf_mod before calculating the min_error, by adding bc_mod (rescaled to mf units) to mf_mod.

### PR DESCRIPTION
**Pull request by hdelongueville**
* **Summary of changes**
The residual error method used to calculate the min error has been fixed to rescale mf_mod to mf units before calculating (y - y_mod).

* **Please check if the PR fulfills these requirements**

- [x] Closes #140 
- [ ] Tests added and passing
- [ ] Documentation and tutorials updated/added
- [ ] Added an entry to the `CHANGELOG.md` file
- [ ] Added any new requirements to `requirements.txt`

### CODE REVIEW

**Comment by hdelongueville** [comment]
I did what I could with my python knowledge. Maybe it could use some better coding.

**Comment by hdelongueville** [comment]
The script is failing when use_bc = False because there is no bc_mod to add to mf_mod.

**Review by brendan-m-murphy — APPROVED** [review]
Looks good!

**Comment by hdelongueville** [comment]
Great thanks!

**Pull request merged**
